language: android

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

notifications:
  email: false
  slack:
    secure: CwD2A4aKRQfTkPnAixS1LE7lk5ZrwDKiKQfGAyo23mpX8Ql5oy4nosiqXKaeHxcL8tQduBFlfCC7+mGQ9HIWot0S2fTIk6K0pJ5NGD9gXGXw/5qh5WVCtbQrlDQ4TTsUGpdXKummIAeWHeE3LN8MHW6X7eNjLVyu8BdOOFhdQVE=

branches:
  except:
    - gh-pages

android:
  components:
    - platform-tools
    - tools

    - build-tools-21.1.1

    - android-21

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./gradlew build
